DROP TABLE Envio;
DROP TABLE Fuente;
DROP TABLE Periodo;

CREATE TABLE Envio (ID number GENERATED AS IDENTITY, cantidadEnviada number(10), Fuenteid number(10) NOT NULL, Periodoid number(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Fuente (id number(10) GENERATED AS IDENTITY, hemisferio varchar2(255), continente varchar2(255), PRIMARY KEY (id));
CREATE TABLE Periodo (id number(10) GENERATED AS IDENTITY, anio number(10) UNIQUE, mes number(10) UNIQUE, PRIMARY KEY (id));
ALTER TABLE Envio ADD CONSTRAINT FKEnvio562135 FOREIGN KEY (Fuenteid) REFERENCES Fuente (id);
ALTER TABLE Envio ADD CONSTRAINT FKEnvio352794 FOREIGN KEY (Periodoid) REFERENCES Periodo (id);

INSERT INTO Fuente (hemisferio,continente) VALUES ('Norte','America');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Sur','America');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Norte','Europa');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Norte','Asia');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Sur','Asia');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Sur','Oceania');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Norte','Africa');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Sur','Africa');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Occidental','America');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Oriental','Asia');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Occidental','Europa');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Oriental','Europa');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Occidental','Africa');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Oriental','Africa');
INSERT INTO Fuente (hemisferio,continente) VALUES ('Oriental','Oceania');

INSERT INTO Periodo (anio,mes) VALUES (2015,1);
INSERT INTO Periodo (anio,mes) VALUES (2016,2);
INSERT INTO Periodo (anio,mes) VALUES (2017,3);
INSERT INTO Periodo (anio,mes) VALUES (2018,4);
INSERT INTO Periodo (anio,mes) VALUES (2019,5);
INSERT INTO Periodo (anio,mes) VALUES (2020,6);

COMMIT;

SELECT 'INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES ('|| floor(dbms_random.value(1, 30)) || ',' || f.id 
    || ',' || p.id || ');' FROM Fuente f, Periodo p;
    

INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (11,1,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (1,2,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (1,3,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (1,4,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (8,5,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (16,6,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (27,7,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (17,8,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (12,9,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (26,10,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (5,11,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (21,12,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (20,13,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (15,14,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (11,15,1);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (27,1,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (8,2,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,3,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (16,4,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (2,5,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (19,6,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (28,7,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (16,8,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (5,9,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (18,10,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (10,11,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (27,12,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (9,13,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (10,14,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (22,15,2);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (28,1,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (12,2,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (24,3,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (18,4,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (16,5,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (1,6,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (16,7,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,8,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,9,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (7,10,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (15,11,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (10,12,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (17,13,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,14,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (20,15,3);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (14,1,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (15,2,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (9,3,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (16,4,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (20,5,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (14,6,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (6,7,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (7,8,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (2,9,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (13,10,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (28,11,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (10,12,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (27,13,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (10,14,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (18,15,4);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (8,1,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (26,2,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (29,3,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (6,4,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (14,5,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (20,6,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (21,7,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (7,8,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (18,9,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (15,10,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,11,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (22,12,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (13,13,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,14,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (6,15,5);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (10,1,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (12,2,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (1,3,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (13,4,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,5,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (29,6,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (11,7,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (15,8,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (17,9,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (23,10,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (12,11,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (10,12,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (4,13,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (15,14,6);
INSERT INTO ENVIO (cantidadEnviada,Fuenteid,Periodoid) VALUES (25,15,6);

COMMIT;
